services:
  nginx:
    image: nginx:latest
    container_name: cafe_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php
    networks:
      - cafe_network
    # restart: always

  php:
    build: ./docker/php
    container_name: cafe_php
    working_dir: /var/www
    volumes:
      - ./src:/var/www/
    depends_on:
      - mysql
    networks:
      - cafe_network
    # restart: always

  mysql:
    image: mysql:8.0
    container_name: cafe_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafe_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cafe_network
    # restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: cafe_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=pass
    networks:
      - cafe_network
    # restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: cafe_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - cafe_network
    # restart: always

volumes:
  mysql_data:
    driver: local

networks:
  cafe_network:
    driver: bridge
